/* Remake by Anatolii Ovcharuk - https: //github.com/Anatolii-Ovcharuk */
/* Description: This is JSX Component for React. */

  /* INSTALLATION */
/*
1. Replace this file "AnimatedBall.jsx" and "AnimatedBall.css" in folder of your project.
2. Add in Application string: import AnimatedBar from './components/AnimatedBall.jsx';
3. Add in Application in return: 
<AnimatedBall /> - With default value;
*/

import React from "react";
import "./AnimatedBall.css"

// const Scene3D = ({ useBall = false }) => <section className="section_scene" style={{
const Scene3D = ({ useBall = false }) => <section className="section_scene" style={{
    display: "block",
    width: "98%",
    height: "100vh"
}}><div className="scene">
<div className="grid">
  <i><i></i><i></i></i>
  <i><i></i><i></i></i>
  <i><i></i><i></i></i>
  <i><i></i><i></i></i>
  <i><i></i><i></i></i>
  <i><i></i><i></i></i>
  <i><i></i><i></i></i>
  <i><i></i><i></i></i>
  <i><i></i><i></i></i>
  <i><i></i><i></i></i>
  <i><i></i><i></i></i>
  <i><i></i><i></i></i>
  <i><i></i><i></i></i>
  <i><i></i><i></i></i>
  <i><i></i><i></i></i>
  <i><i></i><i></i></i>
  <i><i></i><i></i></i>
  <i><i></i><i></i></i>
  <i><i></i><i></i></i>
  <i><i></i><i></i></i>
  <i><i></i><i></i></i>
  <i><i></i><i></i></i>
  <i><i></i><i></i></i>
  <i><i></i><i></i></i>
  <i><i></i><i></i></i>
  <i><i></i><i></i></i>
  <i><i></i><i></i></i>
  <i><i></i><i></i></i>
  <i><i></i><i></i></i>
  <i><i></i><i></i></i>
  <i><i></i><i></i></i>
  <i><i></i><i></i></i>
  <i><i></i><i></i></i>
  <i><i></i><i></i></i>
  <i><i></i><i></i></i>
  <i><i></i><i></i></i>
  <i><i></i><i></i></i>
  <i><i></i><i></i></i>
  <i><i></i><i></i></i>
  <i><i></i><i></i></i>
  <i><i></i><i></i></i>
  <i><i></i><i></i></i>
  <i><i></i><i></i></i>
  <i><i></i><i></i></i>
  <i><i></i><i></i></i>
  <i><i></i><i></i></i>
  <i><i></i><i></i></i>
  <i><i></i><i></i></i>
  <i><i></i><i></i></i>
  <i><i></i><i></i></i>
  <i><i></i><i></i></i>
  <i><i></i><i></i></i>
  <i><i></i><i></i></i>
  <i><i></i><i></i></i>
  <i><i></i><i></i></i>
  <i><i></i><i></i></i>
  <i><i></i><i></i></i>
  <i><i></i><i></i></i>
  <i><i></i><i></i></i>
  <i><i></i><i></i></i>
  <i><i></i><i></i></i>
  <i><i></i><i></i></i>
  <i><i></i><i></i></i>
  <i><i></i><i></i></i>
  <i><i></i><i></i></i>
  <i><i></i><i></i></i>
  <i><i></i><i></i></i>
  <i><i></i><i></i></i>
  <i><i></i><i></i></i>
  <i><i></i><i></i></i>
  <i><i></i><i></i></i>
  <i><i></i><i></i></i>
  <i><i></i><i></i></i>
  <i><i></i><i></i></i>
  <i><i></i><i></i></i>
  <i><i></i><i></i></i>
  <i><i></i><i></i></i>
  <i><i></i><i></i></i>
  <i><i></i><i></i></i>
  <i><i></i><i></i></i>
  <i><i></i><i></i></i>
  <i><i></i><i></i></i>
  <i><i></i><i></i></i>
  <i><i></i><i></i></i>
  <i><i></i><i></i></i>
  <i><i></i><i></i></i>
  <i><i></i><i></i></i>
  <i><i></i><i></i></i>
  <i><i></i><i></i></i>
  <i><i></i><i></i></i>
  <i><i></i><i></i></i>
  <i><i></i><i></i></i>
  <i><i></i><i></i></i>
  <i><i></i><i></i></i>
  <i><i></i><i></i></i>
  <i><i></i><i></i></i>
  <i><i></i><i></i></i>
  <i><i></i><i></i></i>
  <i><i></i><i></i></i>
  <i><i></i><i></i></i>
  <i><i></i><i></i></i>
  <i><i></i><i></i></i>
  <i><i></i><i></i></i>
  <i><i></i><i></i></i>
  <i><i></i><i></i></i>
  <i><i></i><i></i></i>
  <i><i></i><i></i></i>
  <i><i></i><i></i></i>
  <i><i></i><i></i></i>
  <i><i></i><i></i></i>
  <i><i></i><i></i></i>
  <i><i></i><i></i></i>
  <i><i></i><i></i></i>
  <i><i></i><i></i></i>
  <i><i></i><i></i></i>
  <i><i></i><i></i></i>
  <i><i></i><i></i></i>
  <i><i></i><i></i></i>
  <i><i></i><i></i></i>
  <i><i></i><i></i></i>
  <i><i></i><i></i></i>
  <i><i></i><i></i></i>
  <i><i></i><i></i></i>
  <i><i></i><i></i></i>
  <i><i></i><i></i></i>
  <i><i></i><i></i></i>
  <i><i></i><i></i></i>
  <i><i></i><i></i></i>
  <i><i></i><i></i></i>
  <i><i></i><i></i></i>
  <i><i></i><i></i></i>
  <i><i></i><i></i></i>
  <i><i></i><i></i></i>
  <i><i></i><i></i></i>
  <i><i></i><i></i></i>
  <i><i></i><i></i></i>
  <i><i></i><i></i></i>
  <i><i></i><i></i></i>
  <i><i></i><i></i></i>
  <i><i></i><i></i></i>
  <i><i></i><i></i></i>
  <i><i></i><i></i></i>
  <i><i></i><i></i></i>
  <i><i></i><i></i></i>
  <i><i></i><i></i></i>
  <i><i></i><i></i></i>
  <i><i></i><i></i></i>
  <i><i></i><i></i></i>
  <i><i></i><i></i></i>
  <i><i></i><i></i></i>
  <i><i></i><i></i></i>
  <i><i></i><i></i></i>
  <i><i></i><i></i></i>
  <i><i></i><i></i></i>
  <i><i></i><i></i></i>
  <i><i></i><i></i></i>
  <i><i></i><i></i></i>
  <i><i></i><i></i></i>
  <i><i></i><i></i></i>
  <i><i></i><i></i></i>
  <i><i></i><i></i></i>
  <i><i></i><i></i></i>
  <i><i></i><i></i></i>
  <i><i></i><i></i></i>
  <i><i></i><i></i></i>
  <i><i></i><i></i></i>
  <i><i></i><i></i></i>
  <i><i></i><i></i></i>
  <i><i></i><i></i></i>
  <i><i></i><i></i></i>
  <i><i></i><i></i></i>
  <i><i></i><i></i></i>
  <i><i></i><i></i></i>
  <i><i></i><i></i></i>
  <i><i></i><i></i></i>
  <i><i></i><i></i></i>
  <i><i></i><i></i></i>
  <i><i></i><i></i></i>
  <i><i></i><i></i></i>
  <i><i></i><i></i></i>
  <i><i></i><i></i></i>
  <i><i></i><i></i></i>
  <i><i></i><i></i></i>
  <i><i></i><i></i></i>
  <i><i></i><i></i></i>
  <i><i></i><i></i></i>
  <i><i></i><i></i></i>
  <i><i></i><i></i></i>
  <i><i></i><i></i></i>
  <i><i></i><i></i></i>
  <i><i></i><i></i></i>
  <i><i></i><i></i></i>
  <i><i></i><i></i></i>
  <i><i></i><i></i></i>
  <i><i></i><i></i></i>
  <i><i></i><i></i></i>
  <i><i></i><i></i></i>
  <i><i></i><i></i></i>
  <i><i></i><i></i></i>
  <i><i></i><i></i></i>
  <i><i></i><i></i></i>
  <i><i></i><i></i></i>
  <i><i></i><i></i></i>
  <i><i></i><i></i></i>
  <i><i></i><i></i></i>
  <i><i></i><i></i></i>
  <i><i></i><i></i></i>
  <i><i></i><i></i></i>
  <i><i></i><i></i></i>
  <i><i></i><i></i></i>
  <i><i></i><i></i></i>
  <i><i></i><i></i></i>
  <i><i></i><i></i></i>
  <i><i></i><i></i></i>
  <i><i></i><i></i></i>
  <i><i></i><i></i></i>
  <i><i></i><i></i></i>
  <i><i></i><i></i></i>
  <i><i></i><i></i></i>
  <i><i></i><i></i></i>
  <i><i></i><i></i></i>
  <i><i></i><i></i></i>
  <i><i></i><i></i></i>
  <i><i></i><i></i></i>
  <i><i></i><i></i></i>
  <i><i></i><i></i></i>
  <i><i></i><i></i></i>
  <i><i></i><i></i></i>
  <i><i></i><i></i></i>
  <i><i></i><i></i></i>
  <i><i></i><i></i></i>
  <i><i></i><i></i></i>
  <i><i></i><i></i></i>
  <i><i></i><i></i></i>
  <i><i></i><i></i></i>
  <i><i></i><i></i></i>
  <i><i></i><i></i></i>
  <i><i></i><i></i></i>
  <i><i></i><i></i></i>
  <i><i></i><i></i></i>
  <i><i></i><i></i></i>
  <i><i></i><i></i></i>
  <i><i></i><i></i></i>
  <i><i></i><i></i></i>
  <i><i></i><i></i></i>
  <i><i></i><i></i></i>
  <i><i></i><i></i></i>
  <i><i></i><i></i></i>
  <i><i></i><i></i></i>
  <i><i></i><i></i></i>
  <i><i></i><i></i></i>
  <i><i></i><i></i></i>
  <i><i></i><i></i></i>
  <i><i></i><i></i></i>
  <i><i></i><i></i></i>
  <i><i></i><i></i></i>
</div>
{/* {useBall && <div className="ball">
  <i></i>
</div>} */}
</div></section>;

export default Scene3D;
